# Generated by Django 5.0.9 on 2026-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_dnc_phone_idx_campaigns_d_phone_n_517050_idx_and_more'),
        ('leads', '0002_attempt_note'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_primary_1d2722_idx',
            old_name='lead_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_is_acti_c7b69b_idx',
            old_name='lead_active_idx',
        ),
        migrations.RenameIndex(
            model_name='leadattempt',
            new_name='leads_leada_campaig_8d7beb_idx',
            old_name='attempt_campaign_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID from external CRM system', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.SmallIntegerField(default=5, help_text='1=highest, 10=lowest'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, help_text='Import source / list name', max_length=100),
        ),
        migrations.AlterField(
            model_name='leadattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['external_id'], name='leads_lead_externa_2b2b21_idx'),
        ),
    ]
