# Generated by Codex on 2026-04-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0003_rename_lead_phone_idx_leads_lead_primary_1d2722_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.leadbatch'),
        ),
        migrations.AddIndex(
            model_name='leadbatch',
            index=models.Index(fields=['name'], name='leads_leadb_name_418e73_idx'),
        ),
    ]
