# Generated by Django 5.0.9 on 2026-04-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadbatch_lead_batches'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leadbatch',
            new_name='leads_leadb_name_6e072e_idx',
            old_name='leads_leadb_name_418e73_idx',
        ),
    ]
