# Generated by Django 5.0.9 on 2026-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentstatus',
            new_name='agents_agen_status_71bd67_idx',
            old_name='agent_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agentstatus',
            new_name='agents_agen_active__3f28cf_idx',
            old_name='agent_campaign_status_idx',
        ),
        migrations.AlterField(
            model_name='agentstatus',
            name='break_time_today',
            field=models.PositiveIntegerField(default=0, help_text='seconds'),
        ),
        migrations.AlterField(
            model_name='agentstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agentstatus',
            name='talk_time_today',
            field=models.PositiveIntegerField(default=0, help_text='seconds'),
        ),
        migrations.AlterField(
            model_name='calldisposition',
            name='auto_applied',
            field=models.BooleanField(default=False, help_text='True if applied by auto-wrapup timeout'),
        ),
        migrations.AlterField(
            model_name='calldisposition',
            name='callback_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled callback time (if disposition = callback)', null=True),
        ),
        migrations.AlterField(
            model_name='calldisposition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
