# Generated by Django 5.0.9 on 2026-04-07 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_rename_agent_status_idx_agents_agen_status_71bd67_idx_and_more'),
        ('campaigns', '0002_rename_dnc_phone_idx_campaigns_d_phone_n_517050_idx_and_more'),
        ('leads', '0003_rename_lead_phone_idx_leads_lead_primary_1d2722_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pause Code',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='calldisposition',
            name='auto_applied',
        ),
        migrations.AlterField(
            model_name='calldisposition',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calldisposition',
            name='callback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldisposition',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='calldisposition',
            name='disposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.disposition'),
        ),
        migrations.AlterField(
            model_name='calldisposition',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead'),
        ),
        migrations.CreateModel(
            name='AgentLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Login Log',
                'ordering': ['-login_at'],
            },
        ),
        migrations.AddField(
            model_name='agentstatus',
            name='login_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_statuses', to='agents.agentloginlog'),
        ),
        migrations.AddField(
            model_name='agentstatus',
            name='pause_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.pausecode'),
        ),
        migrations.AddIndex(
            model_name='agentloginlog',
            index=models.Index(fields=['user', '-login_at'], name='agents_agen_user_id_8c8fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='agentloginlog',
            index=models.Index(fields=['user', 'login_at'], name='agents_agen_user_id_f71799_idx'),
        ),
    ]
