# Generated by Django 5.0.9 on 2026-04-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_pausecode_remove_calldisposition_auto_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstatus',
            name='active_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
