# Generated by Django 5.0.9 on 2026-04-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agentstatus_active_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstatus',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('ready', 'Ready'), ('ringing', 'Ringing'), ('on_call', 'On Call'), ('wrapup', 'Wrap-up'), ('break', 'Break'), ('training', 'Training')], default='offline', max_length=20),
        ),
    ]
