# Generated by Django 5.0.9 on 2026-04-04 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('leads', '0002_attempt_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calllog',
            new_name='calls_calll_campaig_f6e270_idx',
            old_name='call_campaign_idx',
        ),
        migrations.RenameIndex(
            model_name='calllog',
            new_name='calls_calll_agent_i_623e4e_idx',
            old_name='call_agent_idx',
        ),
        migrations.RenameIndex(
            model_name='calllog',
            new_name='calls_calll_channel_0ef579_idx',
            old_name='call_channel_idx',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Talk duration in seconds'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='ring_duration',
            field=models.PositiveIntegerField(default=0, help_text='Ring time in seconds'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('completed', 'Completed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('abandoned', 'Abandoned')], default='initiated', max_length=20),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['lead', '-started_at'], name='calls_calll_lead_id_8ce17f_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['status', '-started_at'], name='calls_calll_status_9e4bbe_idx'),
        ),
    ]
