# Generated by Django 5.0.9 on 2026-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysnapshot',
            name='avg_talk_time',
            field=models.PositiveIntegerField(default=0, help_text='seconds'),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='total_talk_time',
            field=models.PositiveIntegerField(default=0, help_text='seconds'),
        ),
    ]
