# Generated by Django 5.0.9 on 2026-04-07 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_dnc_phone_idx_campaigns_d_phone_n_517050_idx_and_more'),
        ('reports', '0002_alter_dailysnapshot_avg_talk_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('login_time', models.PositiveIntegerField(default=0, help_text='Total login seconds')),
                ('talk_time', models.PositiveIntegerField(default=0, help_text='Total talk seconds')),
                ('break_time', models.PositiveIntegerField(default=0, help_text='Total break seconds')),
                ('wrapup_time', models.PositiveIntegerField(default=0, help_text='Total wrapup seconds')),
                ('calls_dialed', models.PositiveIntegerField(default=0)),
                ('calls_answered', models.PositiveIntegerField(default=0)),
                ('calls_transferred', models.PositiveIntegerField(default=0)),
                ('dispositions_sale', models.PositiveIntegerField(default=0)),
                ('dispositions_dnc', models.PositiveIntegerField(default=0)),
                ('dispositions_callback', models.PositiveIntegerField(default=0)),
                ('dispositions_other', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Agent Daily Log',
                'ordering': ['-date'],
                'unique_together': {('date', 'agent', 'campaign')},
            },
        ),
    ]
