from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('telephony', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='other', max_length=30)),
                ('outcome', models.CharField(default='recycle', max_length=20)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('hotkey', models.CharField(blank=True, max_length=1)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={'verbose_name': 'Disposition', 'ordering': ['sort_order', 'name']},
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('caller_id', models.CharField(blank=True, max_length=50)),
                ('dial_prefix', models.CharField(blank=True, max_length=20)),
                ('dial_mode', models.CharField(default='predictive', max_length=20)),
                ('dial_ratio', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('max_dial_ratio', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('min_dial_ratio', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('dial_timeout', models.PositiveIntegerField(default=30)),
                ('abandon_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('hopper_level', models.PositiveIntegerField(default=100)),
                ('hopper_size', models.PositiveIntegerField(default=500)),
                ('lead_order', models.CharField(default='sequential', max_length=20)),
                ('amd_enabled', models.BooleanField(default=False)),
                ('amd_action', models.CharField(default='hangup', max_length=20)),
                ('enable_recording', models.BooleanField(default=True)),
                ('recording_mode', models.CharField(default='answered', max_length=20)),
                ('call_hour_start', models.TimeField(default='09:00')),
                ('call_hour_end', models.TimeField(default='21:00')),
                ('respect_timezone', models.BooleanField(default=True)),
                ('wrapup_timeout', models.PositiveIntegerField(default=60)),
                ('auto_wrapup_enabled', models.BooleanField(default=False)),
                ('auto_wrapup_timeout', models.PositiveIntegerField(default=120)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('retry_delay_minutes', models.PositiveIntegerField(default=60)),
                ('use_system_dnc', models.BooleanField(default=True)),
                ('use_campaign_dnc', models.BooleanField(default=True)),
                ('stat_calls_today', models.PositiveIntegerField(default=0)),
                ('stat_answered_today', models.PositiveIntegerField(default=0)),
                ('stat_agents_active', models.PositiveIntegerField(default=0)),
                ('stat_abandon_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('asterisk_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='telephony.asteriskserver')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='telephony.carrier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('auto_wrapup_disposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_wrapup_campaigns', to='campaigns.disposition')),
                ('dispositions', models.ManyToManyField(blank=True, related_name='campaigns', to='campaigns.disposition')),
            ],
            options={'verbose_name': 'Campaign', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='CampaignAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='campaigns.campaign')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={'unique_together': {('campaign', 'agent')}, 'verbose_name': 'Campaign Agent'},
        ),
        migrations.CreateModel(
            name='HopperEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('priority', models.SmallIntegerField(default=5)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('channel_id', models.CharField(blank=True, max_length=100)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('dialed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopper_entries', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopper_entries', to='leads.lead')),
            ],
            options={'verbose_name': 'Hopper Entry', 'ordering': ['-priority', 'queued_at']},
        ),
        migrations.CreateModel(
            name='DNCEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dnc_entries', to='campaigns.campaign')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'DNC Entry', 'unique_together': {('phone_number', 'campaign')}},
        ),
        migrations.AddIndex(model_name='hopperentry', index=models.Index(fields=['campaign', 'status', '-priority', 'queued_at'], name='hopper_campaign_idx')),
        migrations.AddIndex(model_name='dncentry', index=models.Index(fields=['phone_number'], name='dnc_phone_idx')),
    ]
