# Generated by Django 5.0.9 on 2026-04-04 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('leads', '0002_attempt_note'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dncentry',
            new_name='campaigns_d_phone_n_517050_idx',
            old_name='dnc_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='hopperentry',
            new_name='campaigns_h_campaig_5f5f45_idx',
            old_name='hopper_campaign_idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='abandon_rate',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Target max abandon rate %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amd_action',
            field=models.CharField(choices=[('hangup', 'Hang up'), ('message', 'Leave message'), ('agent', 'Send to agent anyway')], default='hangup', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='auto_wrapup_disposition',
            field=models.ForeignKey(blank=True, help_text='Disposition applied on auto-wrapup timeout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_wrapup_campaigns', to='campaigns.disposition'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='caller_id',
            field=models.CharField(blank=True, help_text='Override carrier caller ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dial_mode',
            field=models.CharField(choices=[('preview', 'Preview — agent dials manually'), ('progressive', 'Progressive — one call per available agent'), ('predictive', 'Predictive — algorithm dials ahead')], default='predictive', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dial_prefix',
            field=models.CharField(blank=True, help_text='Prefix added before every number', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dial_ratio',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Calls per available agent (predictive)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dial_timeout',
            field=models.PositiveIntegerField(default=30, help_text='Ring timeout in seconds'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dispositions',
            field=models.ManyToManyField(blank=True, help_text='Dispositions agents can choose for this campaign', related_name='campaigns', to='campaigns.disposition'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='hopper_level',
            field=models.PositiveIntegerField(default=100, help_text='Target leads to keep in hopper'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='hopper_size',
            field=models.PositiveIntegerField(default=500, help_text='Maximum hopper capacity'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='lead_order',
            field=models.CharField(choices=[('sequential', 'Sequential'), ('random', 'Random'), ('priority', 'Priority (highest first)'), ('newest', 'Newest leads first'), ('oldest', 'Oldest leads first')], default='sequential', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='recording_mode',
            field=models.CharField(choices=[('all', 'All calls'), ('answered', 'Answered only')], default='answered', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='respect_timezone',
            field=models.BooleanField(default=True, help_text='Use lead timezone for call hours'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='wrapup_timeout',
            field=models.PositiveIntegerField(default=60, help_text='Seconds agent stays in wrapup'),
        ),
        migrations.AlterField(
            model_name='campaignagent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='category',
            field=models.CharField(choices=[('sale', 'Sale / Converted'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('callback', 'Callback'), ('dnc', 'Do Not Call'), ('not_interested', 'Not Interested'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='color',
            field=models.CharField(default='#6B7280', help_text='Hex color for UI badge', max_length=7),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='hotkey',
            field=models.CharField(blank=True, help_text='Single keyboard shortcut key', max_length=1),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System dispositions cannot be deleted'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='outcome',
            field=models.CharField(choices=[('complete', 'Mark complete — no further attempts'), ('recycle', 'Recycle — attempt again later'), ('dnc', 'Add to DNC list'), ('callback', 'Schedule callback')], default='recycle', max_length=20),
        ),
        migrations.AlterField(
            model_name='dncentry',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Null = system-wide DNC', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dnc_entries', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='dncentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hopperentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hopperentry',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('dialing', 'Dialing'), ('answered', 'Answered'), ('completed', 'Completed'), ('dropped', 'Dropped — no agent'), ('failed', 'Failed — no answer / busy'), ('expired', 'Expired')], default='queued', max_length=20),
        ),
        migrations.AddIndex(
            model_name='hopperentry',
            index=models.Index(fields=['status', 'queued_at'], name='campaigns_h_status_c8d045_idx'),
        ),
    ]
