# Generated by Django 5.0.9 on 2026-04-04 09:34

import telephony.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteriskserver',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='caller_id',
            field=models.CharField(blank=True, help_text='Default outbound caller ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='dial_prefix',
            field=models.CharField(blank=True, help_text='Prefix prepended to all dialed numbers', max_length=20),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='host',
            field=models.CharField(help_text='Carrier SIP host / IP', max_length=200),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='secret',
            field=models.CharField(default=telephony.models._generate_secret, help_text='SIP password', max_length=64),
        ),
    ]
