# Generated by Django 5.0.9 on 2026-04-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0002_alter_asteriskserver_id_alter_carrier_caller_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='dialplan_code',
            field=models.TextField(blank=True, help_text='Raw Asterisk dialplan code for this carrier'),
        ),
    ]
